export const monthMap = new Map();
monthMap.set(1, 'jan')
monthMap.set(2, 'feb')
monthMap.set(3, 'mar')
monthMap.set(4, 'apr')
monthMap.set(5, 'may')
monthMap.set(6, 'jun')
monthMap.set(7, 'jul')
monthMap.set(8, 'aug')
monthMap.set(9, 'sep')
monthMap.set(10, 'oct')
monthMap.set(11, 'nov')
monthMap.set(12, 'dec')

export const reverseMonthMap = new Map();
reverseMonthMap.set('jan', 1)
reverseMonthMap.set('feb', 2)
reverseMonthMap.set('mar', 3 )
reverseMonthMap.set('apr', 4)
reverseMonthMap.set('may', 5)
reverseMonthMap.set('jun', 6)
reverseMonthMap.set('jul', 7)
reverseMonthMap.set('aug', 8)
reverseMonthMap.set('sep', 9)
reverseMonthMap.set('oct', 10)
reverseMonthMap.set('nov', 11)
reverseMonthMap.set('dec', 12)